import type { Metadata } from "next";
import { Nunito, Comfortaa, Playfair_Display } from "next/font/google";

import "./globals.css";
import NavBar from "@/components/NavBar";

const nunito = Nunito({
  variable: "--font-Nunito",
  subsets: ["latin"],
});
const comfortaa = Comfortaa({
  weight: ["400", "700"], // Or your desired weights
  style: ["normal"], // Or your desired styles
  subsets: ["latin"], // Choose your desired character subsets
  display: "swap", // Recommended for better user experience
  variable: "--comfortaa-font", // Optional, for CSS variables
});
const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.className} ${comfortaa.className} ${playfairDisplay.className} antialiased bg-slate-100 dark:bg-slate-900`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
